### ISSUE TITLE
Support for geometry?

### ISSUE THREAD

**Issue by adriennn** [larapack/doctrine-support#4]
Is there any plans to extend the plugin to support geometry columns?

**Comment by marktopper** [comment]
I am not familiar with geometry columns.
Could you please describe how this should work correctly integrated into Laravel.
Also what database drivers does this support?

NOTE: Sorry about the late reply.

**Comment by adriennn** [comment]
Hi Mark, sorry for an even later reply - I was troubleshooting an issue with migrations on laravel back then. I ended up using a fix provided in this [thread](https://github.com/laravel/framework/issues/1186) . Which does'nt actually require the use of doctrine-support so I'll close this issue.
