### ISSUE TITLE
Call to undefined method Illuminate\Database\Connection::resolverFor()

### ISSUE THREAD

**Issue by tokkerbaz** [larapack/doctrine-support#7]
Hey Mark,
I'm using laravel 5.3.* .  voyager ^0.10.0.
when I last updated my composer. It throw me an error like this: 
`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Database\Connection::resolverFor()
`

**Comment by marktopper** [comment]
Thanks, I will make a check for this.

**Comment by marktopper** [comment]
Can you test if `v0.1.3` works for you? Cause then it will be easier for me to find the issue.

**Comment by marktopper** [comment]
Okay, seems like `ResolveFor` is a Laravel 5.4+ method.
Sorry for not turning this into a major release.

Just force your end to use `v0.1.3` and you should be good to go.
